### ISSUE TITLE
Main page down/not there

### ISSUE THREAD

**Issue by Dannyx1604** [NorthDevelopment/NorthClient#11]
The main page(northdevelopment.ga) is not reachable, the demo is:
![grafik](https://user-images.githubusercontent.com/107413165/219854701-37ec29b6-f236-4f11-bb74-84538e94d536.png)

**Comment by jojobingsa** [comment]
Watch at the discord

**Comment by jojobingsa** [comment]
https://demo.northdevelopment.ga/
