### ISSUE TITLE
Discord Auth is broken

### ISSUE THREAD

**Issue by newtondotcom** [NorthDevelopment/NorthClient#13]
Using Discord Auth 2.0, I ve the following error : 
`/home/container/node_modules/node-fetch/lib/index.js:273
                                return Body.Promise.reject(new FetchError('invalid json response body at ${_this2.url} reason: ${err.message}', 'invalid-json'));
                                                           ^
FetchError: invalid json response body at https://petitelectronique.site/auth/login reason: Unexpected token < in JSON at position 0
    at /home/container/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/container/routes/auth/discord.js:257:35 {
  type: 'invalid-json'
}
Node.js v18.14.2`

**Comment by jojobingsa** [comment]
Is fixt in v2.1.0
