### ISSUE TITLE
Pterodactyl API

### ISSUE THREAD

**Issue by newtondotcom** [NorthDevelopment/NorthClient#15]
In `/[routes]/[auth]/email.js`, line `20`, you are making an api call using : 
`${settings.pterodactyl.domain}/api/application/users/${await db.get(`users-${req.query.email}`)}?include=servers`
but the api documentation states that it should be : 
`${settings.pterodactyl.domain}/api/application/users/ID?include=servers`
It shouldnt be email but more id.

**Comment by jojobingsa** [comment]
Can u report ur error on discord in the ticket system?
