### ISSUE TITLE
Servers will not create

### ISSUE THREAD

**Issue by Jax-Danger** [NorthDevelopment/NorthClient#21]
After entering all information with 7Gb ram 15gb disk and 350% cpu on my account, the server does not create. It's a simple but major bug and I have zero idea what to do.

**Comment by MindblownDK** [comment]
i have same problem, the default package is minimum:
1024 ram
1024 Disk
100 CPU

Yet when i enter these variables, it wont create this is my error log from browser
https://imgur.com/a/ONRQ8Bl

**Comment by Nefnief-tech** [comment]
You have to edit the MAX settings for the egg in the settings.yml

**Comment by MindblownDK** [comment]
sorry to ping again but it didnt work for me... i might have done it wrong very possible...
https://imgur.com/MPr5drl
https://imgur.com/yCp2Big

Edit:
Is it because of the PREMIUMLOCATION error?
and cannot seem to find anything related to it...

**Comment by jojobingsa** [comment]
We are working on the bug

**Comment by Jax-Danger** [comment]
good to know
