### ISSUE TITLE
Connection don't work

### ISSUE THREAD

**Issue by Antoineofficiel** [NorthDevelopment/NorthClient#23]
I have entered the correct username and password and it still does not work.
![image](https://github.com/NorthDevelopment/NorthClient/assets/109846246/d9ecaefa-e862-4874-a69b-3601fea6917f)
![image](https://github.com/NorthDevelopment/NorthClient/assets/109846246/5f6e4cca-35bf-46f9-8632-fd9453beeed3)

**Comment by jojobingsa** [comment]
dirent db
