### ISSUE TITLE
Bug Idk 

### ISSUE THREAD

**Issue by dadevguy** [NorthDevelopment/NorthClient#38]
![image](https://github.com/NorthDevelopment/NorthClient/assets/95925949/4cde1484-2aee-40c3-9e28-9ce164f069c7)
People can make unlimited accounts without any kind of verification even though i've disabled signups

**Comment by recabasic** [comment]
https://github.com/NorthDevelopment/NorthClient/blob/main/routes/auth/email.js
Its because, there is no such option for email auth. The password generator is only for Discord Oauth2.
