### ISSUE TITLE
demo page / website down

### ISSUE THREAD

**Issue by Taylor-Hinote** [NorthDevelopment/NorthClient#7]
Your main page is down including your demo

![image](https://user-images.githubusercontent.com/117930865/211103527-15f3102e-7bb9-4685-a4a5-aa7ba28ebf52.png)

**Comment by unknown97834** [comment]
I think it is Not setup now

**Comment by jojobingsa** [comment]
Gonna fix it now.

**Comment by jessy2027** [comment]
The site returns the error "too many redirects"

**Comment by jojobingsa** [comment]
At the moment we try to fix the Server Create Error.

**Comment by jojobingsa** [comment]
https://demo.northdevelopment.ga/ Demo is back online
