### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by hfelashry** [NorthDevelopment/NorthClient#8]
I cannot find docs anywhere or cant even join the discord server

**Comment by jojobingsa** [comment]
Comming Soon.....

**Comment by hfelashry** [comment]
> Comming Soon.....

Ok 👍

**Comment by jojobingsa** [comment]
If u need Help join DC its a new link in. https://discord.gg/fUvK2jed34

**Comment by jojobingsa** [comment]
https://docs.northdevelopment.ga/
